name: Publish Book

on:
  workflow_dispatch:
  push:
    branches: main

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          target: gh-pages
          path: book
          tinytex: true 
          version: 1.6.42
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.3"
      
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "book/.python-version"
      - run: uv pip install -r book/requirements.txt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions


      